# Generated by Django 3.0.3 on 2020-04-07 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TODO_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('contributors', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('todo_template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.TODO_Template')),
            ],
            bases=('todo.todo_template',),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('todo_template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.TODO_Template')),
                ('_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.List')),
            ],
            bases=('todo.todo_template',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('todo_template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.TODO_Template')),
                ('_user', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('todo.todo_template',),
        ),
        migrations.AddField(
            model_name='list',
            name='_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Project'),
        ),
    ]
