# Generated by Django 3.0.3 on 2020-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_merge_20200417_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_template',
            name='collapsed',
            field=models.BooleanField(default=True),
        ),
    ]
