# Generated by Django 3.0.3 on 2020-04-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='_project',
            new_name='parent_obj',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='_user',
            new_name='parent_obj',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='_list',
            new_name='parent_obj',
        ),
    ]
