# Generated by Django 3.0.3 on 2020-04-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200407_2341'),
    ]

    operations = [
    ]
