# Generated by Django 3.0.3 on 2020-04-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_template_collapsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_template',
            name='title',
            field=models.CharField(default='[ Title ]', max_length=100),
        ),
    ]
